// const idade = 17;
// console.log("É maior de idade");
// console.log("É menor de idade");
// if (idade >= 18) {
//     console.log("É maior de idade");
// } else {
//     console.log("É menor de idade");
// }

// const notaDoAluno = 8;

// if (notaDoAluno >= 9) {
//     console.log('Nota excelente');
// } else if (notaDoAluno >= 4) {
//     console.log('Nota mediana');
// } else {
//     console.log('Nota ruim');
// }
idade >= 18 ? console.log('maior de idade') : console.log('menor de idade')
const idade = 36
notaDoAluno >= 7 ? console.log('boa'):console.log('ruim')