
// const idadeVinny = 36;
// const minhaIdade = 35;
const saoIguais = idadeVinny == minhaIdade;
console.log('São iguais? ', saoIguais);
// const comparacao = idadeVinny > minhaIdade;
// console.log('É maior? ', comparacao);
const comparacao = idadeVinny < minhaIdade;
console.log('É menor? ', comparacao);
const idade = 36;
const idadeIrmao = 16;
const souMaiorDeIdade = idade >= 18;
const irmaoMaiorDeIdade = idadeIrmao >= 18;
console.log('Sou maior de idade? ', souMaiorDeIdade);
console.log('Meu irmão é maior de idade? ', irmaoMaiorDeIdade);
const idadeVinny = 36;
const minhaIdade = "36";
// const comparacaoEstrita = minhaIdade === idadeVinny;
// console.log('São estritamente iguais?', comparacaoEstrita);
const comparacaoEstrita = minhaIdade !== idadeVinny;
console.log('São estritamente diferentes?', comparacaoEstrita);